### PR TITLE
fix(server): the provided password must use unique value

### LINKED ISSUE #1485: return warning message when a key is generated with the same password
PUT /access-keys/1
{"id":"1","method":"aes-192-gcm","name":"name-1","password":"P@SsW0rD","limit":{"bytes":10000}}

response : 201

PUT /access-keys/2
{"id":"2","method":"aes-192-gcm","name":"name-2","password":"P@SsW0rD","limit":{"bytes":10000}}

response: 201

By making two different keys but with the same password.

The token that is created is the same for both, and the problem that arises is that the consumed transfer usage is calculated for one of the keys.

According to this, there is a logical problem and it is better to avoid creating keys with the same password

### PR DESCRIPTION
**Pull request by murka**
Fix #1485

### CODE REVIEW

File: src/shadowbox/server/server_access_key.ts [hunk 1]
```diff
@@ -196,6 +196,16 @@ export class ServerAccessKeyRepository implements AccessKeyRepository {
...
     }
+
+    const accessKeys = this.listAccessKeys();
+    const isPasswordConflict = accessKeys.some(
+      (accessKey) => accessKey.proxyParams.password == params?.password
+    );
+
+    if (isPasswordConflict) {
+      throw new errors.PasswordConflict();
+    }
```
Comment (fortuna) [inline src/shadowbox/server/server_access_key.ts:207]: Just making it more compact and grouping the password check logic.:
```suggestion
    const isPasswordConflict = this.listAccessKeys().some(
      (accessKey) => accessKey.proxyParams.password == params?.password
    );
    if (isPasswordConflict) {
      throw new errors.PasswordConflict();
    }
```

File: src/shadowbox/server/server_access_key.ts [hunk 2]
```diff
@@ -196,6 +196,16 @@ export class ServerAccessKeyRepository implements AccessKeyRepository {
...
       id = this.generateId();
     }
+
+    const accessKeys = this.listAccessKeys();
+    const isPasswordConflict = accessKeys.some(
+      (accessKey) => accessKey.proxyParams.password == params?.password
+    );
+
+    if (isPasswordConflict) {
+      throw new errors.PasswordConflict();
```
Comment (fortuna) [inline src/shadowbox/server/server_access_key.ts:206]: Can you pass the conflicting key to the error, so it's easier to debug?

File: src/shadowbox/model/errors.ts [hunk 3]
```diff
@@ -53,3 +53,9 @@ export class AccessKeyConflict extends OutlineError {
     super(`Access key "${accessKeyId}" conflict`);
   }
 }
+
+export class PasswordConflict extends OutlineError {
+  constructor() {
+    super('Some access key have same password');
+  }
```
Comment (fortuna) [inline src/shadowbox/model/errors.ts:60]: I think something like this will be more helpful to the user:

```suggestion
  constructor(accessKey AccessKey) {
    super(`Access key ${accessKey} has the same password. Please specify a unique password for each access key');
  }
```

**Review by fortuna — CHANGES_REQUESTED** [review]

File: src/shadowbox/model/errors.ts (hunk 3 above)
Comment (fortuna) [reply src/shadowbox/model/errors.ts:60]: I'm sorry, I meant `AccessKeyId`, like we do in `AccessKeyNotFound`:
```suggestion
  constructor(accessKeyId?: AccessKeyId) {
    super(`Access key ${accessKeyId} has the same password. Please specify a unique password for each access key');
  }
```

**Review by fortuna — APPROVED** [review]
Thanks for the fix!
